select
    recommendationid,
    appid,
    author_steamid,
    cast(created_at as date) as date,
    author_num_games_owned,
    author_num_reviews,
    author_playtime_forever,
    author_playtime_at_review,
    author_playtime_last_two_weeks,
    author_last_played_at,
    language,
    voted_up,
    votes_up,
    votes_funny,
    weighted_vote_score,
    comment_count,
    steam_purchase,
    received_for_free,
    written_during_early_access,
    hidden_in_steam_china,
    steam_china_location
from {{ ref('stg_steam') }}