columns:
  recommendationid: BIGINT
  appid: BIGINT
  game: VARCHAR
  author_steamid: BIGINT
  author_num_games_owned: INTEGER
  author_num_reviews: INTEGER
  author_playtime_forever: BIGINT
  author_playtime_last_two_weeks: BIGINT
  author_playtime_at_review: BIGINT
  author_last_played: BIGINT
  language: VARCHAR
  review: VARCHAR
  timestamp_created: BIGINT
  timestamp_updated: BIGINT
  voted_up: BOOLEAN
  votes_up: INTEGER
  votes_funny: INTEGER
  weighted_vote_score: DOUBLE
  comment_count: INTEGER
  steam_purchase: BOOLEAN
  received_for_free: BOOLEAN
  written_during_early_access: BOOLEAN
  hidden_in_steam_china: BOOLEAN
  steam_china_location: VARCHAR
path: "s3a://%s/silver"